services:
  ankorar_dev_database:
    container_name: ankorar_dev_database
    image: "postgres:18.0-alpine"
    ports:
      - 5433:5432
    env_file:
      - ../.env
  ankorar_dev_mailcatcher:
    container_name: ankorar_dev_mailcatcher
    image: "sj26/mailcatcher"
    ports:
      - 1080:1080
      - 1025:1025
